version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: flaks_app
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: alarmer_db
    volumes:
      - db-data:/var/lib/postgresql/data_1.2
    networks:
      - app-network
  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    ports:
      - "80:5001"
    environment:
      - TZ=Europe/Moscow
    networks:
      - app-network
  email_service:
    build: ./emails_service/
    container_name: email_service
    environment:
      - TZ=Europe/Moscow
     #УЧЕТНЫЕ ДАННЫЕ ДЛЯ ПОЧТЫ
      - ML_USER=rst\monitoring_rst3
      - ML_PASSWORD=Qq12345
      - ML_HOST=mail.land-group.ru
     #Учетные данные для таблицы
      - TABLE_ID=11lcbsr5nQmcOtL5rcT4YOAyMS1ix6db1E8VWnZq3YLk
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
volumes:
  db-data:

