version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: flaks_app
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: alarmer_db
    volumes:
      - db-data:/var/lib/postgresql/data_1.2
    networks:
      - app-network
  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    ports:
      - "8081:5001"
    environment:
      - TZ=Europe/Moscow
    networks:
      - app-network
  email_service:
    build: ./emails_service/
    container_name: email_service
    environment:
      - TZ=Europe/Moscow
     #УЧЕТНЫЕ ДАННЫЕ ДЛЯ ПОЧТЫ
      - ML_USER=sm@es-company.ru
      - ML_PASSWORD=fhcTxw7svNSPsCf5cyuM
      - ML_HOST=imap.mail.ru
     #Учетные данные для таблицы
      - TABLE_ID=1SaBKxMO01dobyeMd_1DK5pYA-kG37btXGM4aIRssXCo
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
volumes:
  db-data:

